### ISSUE TITLE
Does NVIDIA GPU work on this

### ISSUE THREAD

**Issue by knittycatkitty** [soulomoon/Dell-Precision-5510-OSX#3]
I just got myself this same exact laptop and was pleasantly surprised to see you have a whole repo up for this already. 

I'm trying to find information whether the dGPU has ever been considered working, especially on Mojave where they don't even have web drivers anymore at the moment for NVIDIA

**Comment by PLChinDev** [comment]
I have not been able to locate any information about Nvidia on Mojave. Intel graphics are sufficient for my use case.

**Comment by soulomoon** [comment]
@knittycatkitty I do not think this NVIDIA will work under macos, since it use a nasty technology: Nvidia Optimus, basically this nvidia gpu need the intel gpu to disply the handled content for it which work way different than all the macs.

**Comment by knittycatkitty** [comment]
I see, just as I expected. Thank you for the responses. However does this affect acceleration of the iGPU and is there any video routing going through the NVIDIA GPU whatsoever that may hold back acceleration / Metal / QE / CI on the built-in display?

Not sure how NVIDIA Optimus has evolved since the 2012 days.. where it was quite a proprietary mess with each manufacturer having to implement it in their own way
